### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by faziii0** [happinesslz/EPNetV2#11]
Followed all these steps 

The Environment：

Linux (tested on Ubuntu 16.04)
Python 3.7.6
PyTorch 1.20 + CUDA-10.0/10.1
a. Clone the EPNet++ repository.

git clone https://github.com/happinesslz/EPNetV2.git
b. Create conda environment.

conda create -n epnet_plus_plus_open python==3.7.6
conda activate epnet_plus_plus_open
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
pip install -r requirements.txt
c. Build and install the pointnet2_lib, iou3d, roipool3d libraries by executing the following command:

sh build_and_install.sh    ( When I run this command get this error)

FAILED: /home/fazal/Downloads/EPNetV2/lib/utils/sample2grid/build/temp.linux-x86_64-cpython-37/Voxel_gpu.o 
/usr/bin/nvcc  -I/home/fazal/.local/lib/python3.7/site-packages/torch/include -I/home/fazal/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/fazal/.local/lib/python3.7/site-packages/torch/include/TH -I/home/fazal/.local/lib/python3.7/site-packages/torch/include/THC -I/home/fazal/Downloads/EPNetV2/lib/utils/sample2grid -I/home/fazal/anaconda3/envs/epnet/include/python3.7m -c -c /home/fazal/Downloads/EPNetV2/lib/utils/sample2grid/Voxel_gpu.cu -o /home/fazal/Downloads/EPNetV2/lib/utils/sample2grid/build/temp.linux-x86_64-cpython-37/Voxel_gpu.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=gridvoxel_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
/home/fazal/Downloads/EPNetV2/lib/utils/sample2grid/Voxel_gpu.cu(29): warning #177-D: variable "grid_H" was declared but never referenced

/home/fazal/Downloads/EPNetV2/lib/utils/sample2grid/Voxel_gpu.cu(30): warning #177-D: variable "grid_Coor" was declared but never referenced

/home/fazal/Downloads/EPNetV2/lib/utils/sample2grid/Voxel_gpu.cu(106): warning #177-D: variable "grid_H" was declared but never referenced

/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&& __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/fazal/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1906, in _run_ninja_build
    env=env)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    , include_dirs = ['./'],
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/fazal/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/fazal/anaconda3/envs/epnet/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "/home/fazal/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 668, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/fazal/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1578, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/fazal/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by HydrogenWasser** [comment]
how u solved this problem bro

**Comment by syd-21** [comment]
It’s due to cuda mismatch you should first try to install all relevant libraries and cuda toolkit

**Comment by HydrogenWasser** [comment]
> It’s due to cuda mismatch you should first try to install all relevant libraries and cuda toolkit

is that means i have to  install PyTorch 1.20 + CUDA-10.0/10.1 just the same as the enviroment in README markdown 
or i can install with my own enviroment PyTorch 1.90 + CUDA-11.1, i think PyTorch 1.90 + CUDA-11.1 is also match>

**Comment by syd-21** [comment]
share your email. i can send you instructions

**Comment by HydrogenWasser** [comment]
> 

cloud_hua@outlook.com
thx
